# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'HolidayPipeline-conn'
    subscriptionId: '7e820774-5f7f-49b7-8f6a-4f32427eac83'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'HolidayPipeline-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/phartridge/holidaypipeline/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectname holsarmpipe'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployHolidayPLTempl'